### ISSUE TITLE
Can't build the project (node v8.2.1 & npm v5.3.0)

### ISSUE THREAD

**Issue by green2k** [furqanZafar/react-selectize#171]
```
nvm use 8 // Now using node v8.2.1 (npm v5.3.0)
npm install
npm start
```
This is the result: 
```
[15:28:19] Requiring external module livescript
[15:28:19] Using gulpfile ~/git/react-selectize/gulpfile.ls
[15:28:19] Starting 'default'...
[15:28:19] Starting 'build:themes'...
[15:28:19] Starting 'build:src:scripts'...
[15:28:19] Finished 'default' after 13 ms
[15:28:21] Finished 'build:themes' after 1.6 s
[15:28:21] Finished 'build:src:scripts' after 1.62 s
[15:28:21] Starting 'build:src'...
[15:28:21] Finished 'build:src' after 88 μs
[15:28:21] Starting 'watch:themes'...
[15:28:21] Finished 'watch:themes' after 12 ms
[15:28:21] Starting 'watch:src:scripts'...
[15:28:21] Finished 'watch:src:scripts' after 5.02 ms
[15:28:21] Starting 'watch:src'...
[15:28:21] Finished 'watch:src' after 2.33 μs
[15:28:21] Starting 'build:examples:styles'...
[15:28:21] Finished 'build:examples:styles' after 149 ms
[15:28:21] Starting 'watch:examples:styles'...
[15:28:21] Finished 'watch:examples:styles' after 18 ms
[15:28:21] Starting 'build-and-watch:examples:scripts'...
[15:28:26] { '0': 
   { Error: Cannot find module 'react-router/lib/HashHistory' from '/home/pali/git/react-selectize/public/components'
       at /home/pali/git/react-selectize/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
       at process (/home/pali/git/react-selectize/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
       at ondir (/home/pali/git/react-selectize/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
       at load (/home/pali/git/react-selectize/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
       at onex (/home/pali/git/react-selectize/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
       at /home/pali/git/react-selectize/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
       at FSReqWrap.oncomplete (fs.js:152:21)
     stream: 
      Labeled {
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        _options: [Object],
        _wrapOptions: [Object],
        _streams: [Array],
        length: 2,
        label: 'deps' } } }
```

**Comment by ArthurBugan** [comment]
Did you manage to solve this issue with react-router?

**Comment by ArthurBugan** [comment]
I manage to solve by chaging the import of hash-history on App.ls to {hashHistory} = require \react-router/lib and upgrading the version of react-router to 3.0.5
